"""direct message table

Revision ID: 3a897d335a61
Revises: 49c1c01d71d7
Create Date: 2023-12-10 12:32:28.795698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a897d335a61'
down_revision = '49c1c01d71d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('recipient_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('_title', sa.String(length=128), nullable=True),
    sa.Column('_content', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direct_messages_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direct_messages_slug'))

    op.drop_table('direct_messages')
    # ### end Alembic commands ###
