"""remove old models

Revision ID: 8ac694479288
Revises: 3a897d335a61
Create Date: 2023-12-10 19:57:00.255540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ac694479288'
down_revision = '3a897d335a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_comments')
    with op.batch_alter_table('direct_threads', schema=None) as batch_op:
        batch_op.drop_index('ix_direct_threads_slug')

    op.drop_table('direct_threads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_threads',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('direct_threads_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='direct_threads_author_id_fkey'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='direct_threads_recipient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='direct_threads_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('direct_threads', schema=None) as batch_op:
        batch_op.create_index('ix_direct_threads_slug', ['slug'], unique=False)

    op.create_table('direct_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='direct_comments_author_id_fkey'),
    sa.ForeignKeyConstraint(['thread_id'], ['direct_threads.id'], name='direct_comments_thread_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='direct_comments_pkey')
    )
    # ### end Alembic commands ###
